projects:
  app:
    schemaPath: src/schema.graphql
    includes: ['**/*.graphql']
    extensions:
      endpoints:
        default: http://localhost:4000
  db:
    schemaPath: src/generated/prisma.graphql
    includes: ['**/*.graphql']
    extensions:
      prisma: prisma/prisma.yml
      codegen:
        - generator: typescript-client
          language: typescript
          output:
            binding: src/generated/prisma-client/index.ts
